// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurantes.Infrastructure.Context;

#nullable disable

namespace Restaurantes.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240619165038_UpdatedUsuarioConfiguration")]
    partial class UpdatedUsuarioConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurantes.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiasPresenciais")
                        .HasColumnType("int");

                    b.Property<string>("EnderecoDaEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecoMedioPorRefeicao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorDoValeRefeicao")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 19, 13, 50, 38, 334, DateTimeKind.Local).AddTicks(3528),
                            DiasPresenciais = 10,
                            EnderecoDaEmpresa = "Rua Jorge Beretta",
                            Nome = "Eriberto Lima",
                            PrecoMedioPorRefeicao = 5000000m,
                            ValorDoValeRefeicao = 2.000m
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 19, 13, 50, 38, 334, DateTimeKind.Local).AddTicks(3552),
                            DiasPresenciais = 20,
                            EnderecoDaEmpresa = "Street 10",
                            Nome = "Jhon Dee",
                            PrecoMedioPorRefeicao = 5000000m,
                            ValorDoValeRefeicao = 1.000m
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 19, 13, 50, 38, 334, DateTimeKind.Local).AddTicks(3554),
                            DiasPresenciais = 10,
                            EnderecoDaEmpresa = "Rua beltrano azevedo",
                            Nome = "Fulano de tal",
                            PrecoMedioPorRefeicao = 5000000m,
                            ValorDoValeRefeicao = 500m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
